"""
Task Manager - OPENCLAW Autonomous Agent Project
Command-line interface using Click
Generated by OpenClaw Agent
"""

import click
from datetime import datetime
from typing import Optional

from models import Task, Priority
from storage import TaskStorage


@click.group()
def cli():
    """Task Manager - Manage your tasks efficiently."""
    pass


@cli.command()
@click.argument('title')
@click.option('--description', '-d', default='', help='Description of the task')
@click.option('--priority', '-p', type=click.Choice(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']), 
              default='MEDIUM', help='Priority level')
@click.option('--due-date', '-D', type=click.DateTime(formats=['%Y-%m-%d']), 
              help='Due date (YYYY-MM-DD)')
def add(title, description, priority, due_date):
    """Add a new task."""
    storage = TaskStorage()
    
    task = Task(
        id=0,  # Will be set by database
        title=title,
        description=description,
        priority=Priority[priority],
        due_date=due_date
    )
    
    task_id = storage.add_task(task)
    click.echo(f"✓ Task added successfully with ID: {task_id}")


@cli.command()
@click.option('--all', 'show_all', is_flag=True, help='Show all tasks including completed')
def list(show_all):
    """List all tasks."""
    storage = TaskStorage()
    
    if show_all:
        tasks = storage.get_all_tasks()
    else:
        tasks = storage.get_pending_tasks()
    
    if not tasks:
        click.echo("No tasks found.")
        return
    
    click.echo(f"\n{'ID':<5} {'Status':<8} {'Priority':<10} {'Title':<30} {'Due Date':<12}")
    click.echo("-" * 75)
    
    for task in tasks:
        status = "✓ Done" if task.completed else "○ Pending"
        priority_str = task.priority.name
        due_date_str = task.due_date.strftime('%Y-%m-%d') if task.due_date else "-"
        title_display = task.title[:27] + "..." if len(task.title) > 30 else task.title
        
        click.echo(f"{task.id:<5} {status:<8} {priority_str:<10} {title_display:<30} {due_date_str:<12}")
    
    click.echo(f"\nTotal: {len(tasks)} task(s)")


@cli.command()
@click.argument('task_id', type=int)
def complete(task_id):
    """Mark a task as complete."""
    storage = TaskStorage()
    task = storage.get_task(task_id)
    
    if not task:
        click.echo(f"✗ Task with ID {task_id} not found.")
        return
    
    task.mark_complete()
    storage.update_task(task)
    click.echo(f"✓ Task '{task.title}' marked as complete.")


@cli.command()
@click.argument('task_id', type=int)
@click.confirmation_option(prompt='Are you sure you want to delete this task?')
def delete(task_id):
    """Delete a task."""
    storage = TaskStorage()
    task = storage.get_task(task_id)
    
    if not task:
        click.echo(f"✗ Task with ID {task_id} not found.")
        return
    
    storage.delete_task(task_id)
    click.echo(f"✓ Task '{task.title}' deleted successfully.")


@cli.command()
@click.argument('query')
def search(query):
    """Search for tasks."""
    storage = TaskStorage()
    tasks = storage.search_tasks(query)
    
    if not tasks:
        click.echo(f"No tasks found matching '{query}'.")
        return
    
    click.echo(f"\nSearch results for '{query}':\n")
    click.echo(f"{'ID':<5} {'Status':<8} {'Priority':<10} {'Title':<30} {'Due Date':<12}")
    click.echo("-" * 75)
    
    for task in tasks:
        status = "✓ Done" if task.completed else "○ Pending"
        priority_str = task.priority.name
        due_date_str = task.due_date.strftime('%Y-%m-%d') if task.due_date else "-"
        title_display = task.title[:27] + "..." if len(task.title) > 30 else task.title
        
        click.echo(f"{task.id:<5} {status:<8} {priority_str:<10} {title_display:<30} {due_date_str:<12}")
    
    click.echo(f"\nFound: {len(tasks)} task(s)")


@cli.command()
def stats():
    """Show task statistics."""
    storage = TaskStorage()
    all_tasks = storage.get_all_tasks()
    
    total = len(all_tasks)
    completed = sum(1 for t in all_tasks if t.completed)
    pending = total - completed
    
    priority_counts = {}
    for task in all_tasks:
        priority_counts[task.priority.name] = priority_counts.get(task.priority.name, 0) + 1
    
    click.echo("\n=== Task Statistics ===\n")
    click.echo(f"Total Tasks:     {total}")
    click.echo(f"Completed:       {completed} ({completed/total*100:.1f}%)" if total > 0 else "Completed:       0")
    click.echo(f"Pending:         {pending}")
    click.echo("\nBy Priority:")
    for priority, count in sorted(priority_counts.items()):
        click.echo(f"  {priority:<10} {count}")
    click.echo()


if __name__ == '__main__':
    cli()