"""
Task Manager - OPENCLAW Autonomous Agent Project
Graphical User Interface using Tkinter
Generated by OpenClaw Agent
"""

import tkinter as tk
from tkinter import ttk, messagebox, simpledialog, colorchooser
from datetime import datetime, timedelta
from typing import Optional, List

from models import Task, Priority, RepeatFrequency, Tag, SubTask
from storage import TaskStorage


class TaskManagerGUI:
    """Graphical user interface for the Task Manager."""
    
    def __init__(self, root):
        self.root = root
        self.root.title("Task Manager - OPENCLAW")
        self.root.geometry("1200x700")
        
        self.storage = TaskStorage()
        self.current_filter = "all"
        self.selected_task_id = None
        
        self._setup_styles()
        self._create_menu()
        self._create_main_layout()
        self._create_task_list()
        self._create_task_details()
        self._create_toolbar()
        self._load_tasks()
        self._load_tags()
    
    def _setup_styles(self):
        """Setup ttk styles."""
        style = ttk.Style()
        style.theme_use('clam')
        
        # Configure colors for priorities
        style.configure('Priority.LOW.Treeview', background='#90EE90')
        style.configure('Priority.MEDIUM.Treeview', background='#FFD700')
        style.configure('Priority.HIGH.Treeview', background='#FFA500')
        style.configure('Priority.CRITICAL.Treeview', background='#FF6347')
    
    def _create_menu(self):
        """Create menu bar."""
        menubar = tk.Menu(self.root)
        self.root.config(menu=menubar)
        
        # File menu
        file_menu = tk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="File", menu=file_menu)
        file_menu.add_command(label="Backup Database", command=self._backup_database)
        file_menu.add_separator()
        file_menu.add_command(label="Exit", command=self.root.quit)
        
        # Tasks menu
        tasks_menu = tk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="Tasks", menu=tasks_menu)
        tasks_menu.add_command(label="Add Task", command=self._add_task, accelerator="Ctrl+N")
        tasks_menu.add_command(label="Edit Task", command=self._edit_task, accelerator="Ctrl+E")
        tasks_menu.add_command(label="Delete Task", command=self._delete_task, accelerator="Ctrl+D")
        tasks_menu.add_command(label="Complete Task", command=self._complete_task, accelerator="Ctrl+C")
        
        # View menu
        view_menu = tk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="View", menu=view_menu)
        view_menu.add_command(label="Show All Tasks", command=lambda: self._filter_tasks("all"))
        view_menu.add_command(label="Show Pending Tasks", command=lambda: self._filter_tasks("pending"))
        view_menu.add_command(label="Show Completed Tasks", command=lambda: self._filter_tasks("completed"))
        view_menu.add_command(label="Show Overdue Tasks", command=lambda: self._filter_tasks("overdue"))
        view_menu.add_command(label="Show Today's Tasks", command=lambda: self._filter_tasks("today"))
        
        # Tools menu
        tools_menu = tk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="Tools", menu=tools_menu)
        tools_menu.add_command(label="Pomodoro Timer", command=self._open_pomodoro_timer)
        tools_menu.add_command(label="Manage Tags", command=self._manage_tags)
        tools_menu.add_command(label="Analytics", command=self._show_analytics)
        
        # Help menu
        help_menu = tk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="Help", menu=help_menu)
        help_menu.add_command(label="About", command=self._show_about)
        
        # Keyboard shortcuts
        self.root.bind('<Control-n>', lambda e: self._add_task())
        self.root.bind('<Control-e>', lambda e: self._edit_task())
        self.root.bind('<Control-d>', lambda e: self._delete_task())
        self.root.bind('<Control-c>', lambda e: self._complete_task())
    
    def _create_main_layout(self):
        """Create main layout with paned window."""
        self.main_pane = ttk.PanedWindow(self.root, orient=tk.HORIZONTAL)
        self.main_pane.pack(fill=tk.BOTH, expand=True, padx=5, pady=5)
    
    def _create_task_list(self):
        """Create task list panel."""
        list_frame = ttk.LabelFrame(self.main_pane, text="Tasks", padding=10)
        self.main_pane.add(list_frame, weight=2)
        
        # Search box
        search_frame = ttk.Frame(list_frame)
        search_frame.pack(fill=tk.X, pady=(0, 10))
        
        ttk.Label(search_frame, text="Search:").pack(side=tk.LEFT)
        self.search_var = tk.StringVar()
        self.search_var.trace('w', lambda *args: self._search_tasks())
        search_entry = ttk.Entry(search_frame, textvariable=self.search_var)
        search_entry.pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(5, 0))
        
        # Task treeview
        columns = ('ID', 'Title', 'Priority', 'Due Date', 'Status', 'Tags')
        self.task_tree = ttk.Treeview(list_frame, columns=columns, show='headings', height=20)
        
        # Define columns
        self.task_tree.heading('ID', text='ID')
        self.task_tree.heading('Title', text='Title')
        self.task_tree.heading('Priority', text='Priority')
        self.task_tree.heading('Due Date', text='Due Date')
        self.task_tree.heading('Status', text='Status')
        self.task_tree.heading('Tags', text='Tags')
        
        self.task_tree.column('ID', width=50)
        self.task_tree.column('Title', width=250)
        self.task_tree.column('Priority', width=80)
        self.task_tree.column('Due Date', width=100)
        self.task_tree.column('Status', width=80)
        self.task_tree.column('Tags', width=150)
        
        # Scrollbars
        y_scroll = ttk.Scrollbar(list_frame, orient=tk.VERTICAL, command=self.task_tree.yview)
        x_scroll = ttk.Scrollbar(list_frame, orient=tk.HORIZONTAL, command=self.task_tree.xview)
        self.task_tree.configure(yscrollcommand=y_scroll.set, xscrollcommand=x_scroll.set)
        
        # Pack widgets
        self.task_tree.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        y_scroll.pack(side=tk.RIGHT, fill=tk.Y)
        x_scroll.pack(side=tk.BOTTOM, fill=tk.X)
        
        # Bind selection
        self.task_tree.bind('<<TreeviewSelect>>', self._on_task_select)
        self.task_tree.bind('<Double-Button-1>', lambda e: self._edit_task())
    
    def _create_task_details(self):
        """Create task details panel."""
        details_frame = ttk.LabelFrame(self.main_pane, text="Task Details", padding=10)
        self.main_pane.add(details_frame, weight=1)
        
        # Task info
        info_frame = ttk.Frame(details_frame)
        info_frame.pack(fill=tk.X, pady=(0, 10))
        
        ttk.Label(info_frame, text="Title:").grid(row=0, column=0, sticky=tk.W, pady=5)
        self.detail_title = ttk.Label(info_frame, text="", font=('Arial', 12, 'bold'))
        self.detail_title.grid(row=0, column=1, sticky=tk.W, pady=5)
        
        ttk.Label(info_frame, text="Description:").grid(row=1, column=0, sticky=tk.NW, pady=5)
        self.detail_desc = tk.Text(info_frame, height=4, width=30, wrap=tk.WORD, state='disabled')
        self.detail_desc.grid(row=1, column=1, sticky=tk.W, pady=5)
        
        ttk.Label(info_frame, text="Priority:").grid(row=2, column=0, sticky=tk.W, pady=5)
        self.detail_priority = ttk.Label(info_frame, text="")
        self.detail_priority.grid(row=2, column=1, sticky=tk.W, pady=5)
        
        ttk.Label(info_frame, text="Due Date:").grid(row=3, column=0, sticky=tk.W, pady=5)
        self.detail_due = ttk.Label(info_frame, text="")
        self.detail_due.grid(row=3, column=1, sticky=tk.W, pady=5)
        
        ttk.Label(info_frame, text="Status:").grid(row=4, column=0, sticky=tk.W, pady=5)
        self.detail_status = ttk.Label(info_frame, text="")
        self.detail_status.grid(row=4, column=1, sticky=tk.W, pady=5)
        
        ttk.Label(info_frame, text="Tags:").grid(row=5, column=0, sticky=tk.W, pady=5)
        self.detail_tags = ttk.Label(info_frame, text="")
        self.detail_tags.grid(row=5, column=1, sticky=tk.W, pady=5)
        
        ttk.Label(info_frame, text="Repeat:").grid(row=6, column=0, sticky=tk.W, pady=5)
        self.detail_repeat = ttk.Label(info_frame, text="")
        self.detail_repeat.grid(row=6, column=1, sticky=tk.W, pady=5)
        
        ttk.Label(info_frame, text="Pomodoros:").grid(row=7, column=0, sticky=tk.W, pady=5)
        self.detail_pomodoros = ttk.Label(info_frame, text="")
        self.detail_pomodoros.grid(row=7, column=1, sticky=tk.W, pady=5)
        
        # Action buttons
        button_frame = ttk.Frame(details_frame)
        button_frame.pack(fill=tk.X, pady=10)
        
        ttk.Button(button_frame, text="Complete", command=self._complete_task).pack(side=tk.LEFT, padx=2)
        ttk.Button(button_frame, text="Edit", command=self._edit_task).pack(side=tk.LEFT, padx=2)
        ttk.Button(button_frame, text="Delete", command=self._delete_task).pack(side=tk.LEFT, padx=2)
        
        # Sub-tasks section
        subtasks_frame = ttk.LabelFrame(details_frame, text="Sub-Tasks", padding=5)
        subtasks_frame.pack(fill=tk.BOTH, expand=True, pady=10)
        
        self.subtask_list = tk.Listbox(subtasks_frame, height=6)
        self.subtask_list.pack(fill=tk.BOTH, expand=True)
        
        subtask_btn_frame = ttk.Frame(subtasks_frame)
        subtask_btn_frame.pack(fill=tk.X, pady=5)
        
        ttk.Button(subtask_btn_frame, text="Add", command=self._add_subtask).pack(side=tk.LEFT, padx=2)
        ttk.Button(subtask_btn_frame, text="Complete", command=self._complete_subtask).pack(side=tk.LEFT, padx=2)
        
        # Clear details
        self._clear_details()
    
    def _create_toolbar(self):
        """Create toolbar at bottom."""
        toolbar = ttk.Frame(self.root)
        toolbar.pack(fill=tk.X, padx=5, pady=5)
        
        ttk.Button(toolbar, text="Add Task", command=self._add_task).pack(side=tk.LEFT, padx=2)
        ttk.Button(toolbar, text="Refresh", command=self._load_tasks).pack(side=tk.LEFT, padx=2)
        ttk.Button(toolbar, text="Statistics", command=self._show_analytics).pack(side=tk.LEFT, padx=2)
        
        # Status label
        self.status_label = ttk.Label(toolbar, text="Ready")
        self.status_label.pack(side=tk.RIGHT)
    
    def _load_tasks(self):
        """Load tasks into the treeview."""
        # Clear existing items
        for item in self.task_tree.get_children():
            self.task_tree.delete(item)
        
        # Get tasks based on filter
        if self.current_filter == "all":
            tasks = self.storage.get_all_tasks()
        elif self.current_filter == "pending":
            tasks = self.storage.get_pending_tasks()
        elif self.current_filter == "completed":
            all_tasks = self.storage.get_all_tasks()
            tasks = [t for t in all_tasks if t.completed]
        elif self.current_filter == "overdue":
            tasks = self.storage.get_overdue_tasks()
        elif self.current_filter == "today":
            tasks = self.storage.get_tasks_due_today()
        else:
            tasks = self.storage.get_all_tasks()
        
        # Insert tasks
        for task in tasks:
            tags_str = ", ".join([f"#{i}" for i in task.tags[:3]])
            status = "✓" if task.completed else "○"
            due_date = task.due_date.strftime('%Y-%m-%d') if task.due_date else "-"
            
            values = (
                task.id,
                task.title[:40],
                task.priority.name,
                due_date,
                status,
                tags_str
            )
            
            item_id = self.task_tree.insert('', tk.END, values=values, iid=str(task.id))
            
            # Apply priority color
            priority_tag = f'priority.{task.priority.name}'
            colors = {
                'LOW': '#90EE90',
                'MEDIUM': '#FFD700',
                'HIGH': '#FFA500',
                'CRITICAL': '#FF6347'
            }
            
            self.task_tree.tag_configure(priority_tag, background=colors.get(task.priority.name, 'white'))
            self.task_tree.item(item_id, tags=(priority_tag,))
        
        self.status_label.config(text=f"Loaded {len(tasks)} tasks")
    
    def _load_tags(self):
        """Load tags from database."""
        self.all_tags = self.storage.get_all_tags()
    
    def _on_task_select(self, event):
        """Handle task selection."""
        selection = self.task_tree.selection()
        if not selection:
            self._clear_details()
            return
        
        task_id = int(selection[0])
        self.selected_task_id = task_id
        task = self.storage.get_task(task_id)
        
        if task:
            self._display_task_details(task)
    
    def _display_task_details(self, task: Task):
        """Display task details in the details panel."""
        self.detail_title.config(text=task.title)
        
        self.detail_desc.config(state='normal')
        self.detail_desc.delete('1.0', tk.END)
        self.detail_desc.insert('1.0', task.description)
        self.detail_desc.config(state='disabled')
        
        self.detail_priority.config(text=task.priority.name)
        self.detail_due.config(text=task.due_date.strftime('%Y-%m-%d %H:%M') if task.due_date else "None")
        self.detail_status.config(text="Completed" if task.completed else "Pending")
        
        tags_str = ", ".join([f"#{i}" for i in task.tags]) if task.tags else "None"
        self.detail_tags.config(text=tags_str)
        
        repeat_str = task.repeat_frequency.name if task.repeat_frequency != RepeatFrequency.NONE else "None"
        self.detail_repeat.config(text=repeat_str)
        
        pomodoro_str = f"{task.pomodoros_completed}/{task.estimated_pomodoros}"
        self.detail_pomodoros.config(text=pomodoro_str)
        
        # Load sub-tasks
        self.subtask_list.delete(0, tk.END)
        for subtask in task.sub_tasks:
            status = "✓" if subtask.completed else "○"
            self.subtask_list.insert(tk.END, f"{status} {subtask.title}")
    
    def _clear_details(self):
        """Clear task details."""
        self.detail_title.config(text="")
        self.detail_desc.config(state='normal')
        self.detail_desc.delete('1.0', tk.END)
        self.detail_desc.config(state='disabled')
        self.detail_priority.config(text="")
        self.detail_due.config(text="")
        self.detail_status.config(text="")
        self.detail_tags.config(text="")
        self.detail_repeat.config(text="")
        self.detail_pomodoros.config(text="")
        self.subtask_list.delete(0, tk.END)
        self.selected_task_id = None
    
    def _add_task(self):
        """Open dialog to add a new task."""
        dialog = AddTaskDialog(self.root, self.all_tags)
        if dialog.result:
            task = Task(
                id=0,
                title=dialog.result['title'],
                description=dialog.result['description'],
                priority=dialog.result['priority'],
                due_date=dialog.result['due_date'],
                reminder_date=dialog.result['reminder_date'],
                tags=dialog.result['tags'],
                repeat_frequency=dialog.result['repeat_frequency']
            )
            
            self.storage.add_task(task)
            self._load_tasks()
            self.status_label.config(text="Task added successfully")
    
    def _edit_task(self):
        """Open dialog to edit selected task."""
        if not self.selected_task_id:
            messagebox.showwarning("Warning", "Please select a task first")
            return
        
        task = self.storage.get_task(self.selected_task_id)
        if not task:
            return
        
        dialog = EditTaskDialog(self.root, task, self.all_tags)
        if dialog.result:
            # Update task properties
            task.title = dialog.result['title']
            task.description = dialog.result['description']
            task.priority = dialog.result['priority']
            task.due_date = dialog.result['due_date']
            task.reminder_date = dialog.result['reminder_date']
            task.tags = dialog.result['tags']
            task.repeat_frequency = dialog.result['repeat_frequency']
            task.estimated_pomodoros = dialog.result['estimated_pomodoros']
            
            self.storage.update_task(task)
            self._load_tasks()
            self._display_task_details(task)
            self.status_label.config(text="Task updated successfully")
    
    def _delete_task(self):
        """Delete selected task."""
        if not self.selected_task_id:
            messagebox.showwarning("Warning", "Please select a task first")
            return
        
        if messagebox.askyesno("Confirm Delete", "Are you sure you want to delete this task?"):
            self.storage.delete_task(self.selected_task_id)
            self._load_tasks()
            self._clear_details()
            self.status_label.config(text="Task deleted successfully")
    
    def _complete_task(self):
        """Mark selected task as complete."""
        if not self.selected_task_id:
            messagebox.showwarning("Warning", "Please select a task first")
            return
        
        task = self.storage.get_task(self.selected_task_id)
        if not task:
            return
        
        if task.completed:
            messagebox.showinfo("Info", "Task is already completed")
            return
        
        task.mark_complete()
        self.storage.update_task(task)
        self._load_tasks()
        self._display_task_details(task)
        self.status_label.config(text="Task marked as complete")
    
    def _add_subtask(self):
        """Add a sub-task to the selected task."""
        if not self.selected_task_id:
            messagebox.showwarning("Warning", "Please select a task first")
            return
        
        title = simpledialog.askstring("Add Sub-Task", "Enter sub-task title:")
        if title:
            self.storage.add_subtask(self.selected_task_id, title)
            task = self.storage.get_task(self.selected_task_id)
            self._display_task_details(task)
            self.status_label.config(text="Sub-task added")
    
    def _complete_subtask(self):
        """Complete selected sub-task."""
        if not self.selected_task_id:
            messagebox.showwarning("Warning", "Please select a task first")
            return
        
        selection = self.subtask_list.curselection()
        if not selection:
            messagebox.showwarning("Warning", "Please select a sub-task")
            return
        
        # Get sub-task ID (simplified - in production would map properly)
        index = selection[0]
        task = self.storage.get_task(self.selected_task_id)
        if task and index < len(task.sub_tasks):
            subtask = task.sub_tasks[index]
            self.storage.complete_subtask(subtask.id)
            task = self.storage.get_task(self.selected_task_id)
            self._display_task_details(task)
            self.status_label.config(text="Sub-task completed")
    
    def _search_tasks(self):
        """Search tasks based on search term."""
        query = self.search_var.get()
        if not query:
            self._load_tasks()
            return
        
        # Clear existing items
        for item in self.task_tree.get_children():
            self.task_tree.delete(item)
        
        tasks = self.storage.search_tasks(query)
        for task in tasks:
            tags_str = ", ".join([f"#{i}" for i in task.tags[:3]])
            status = "✓" if task.completed else "○"
            due_date = task.due_date.strftime('%Y-%m-%d') if task.due_date else "-"
            
            values = (
                task.id,
                task.title[:40],
                task.priority.name,
                due_date,
                status,
                tags_str
            )
            self.task_tree.insert('', tk.END, values=values, iid=str(task.id))
        
        self.status_label.config(text=f"Found {len(tasks)} tasks matching '{query}'")
    
    def _filter_tasks(self, filter_type):
        """Filter tasks by type."""
        self.current_filter = filter_type
        self._load_tasks()
    
    def _backup_database(self):
        """Create database backup."""
        from pathlib import Path
        backup_path = Path.home() / "task_manager_backups"
        backup_path.mkdir(exist_ok=True)
        
        backup_file = self.storage.create_backup(str(backup_path))
        messagebox.showinfo("Backup", f"Database backed up to:\n{backup_file}")
    
    def _manage_tags(self):
        """Open tag management dialog."""
        dialog = ManageTagsDialog(self.root, self.storage)
        if dialog.refresh_needed:
            self._load_tags()
            self._load_tasks()
    
    def _show_analytics(self):
        """Show task analytics."""
        analytics = self.storage.get_task_analytics()
        
        analytics_window = tk.Toplevel(self.root)
        analytics_window.title("Task Analytics")
        analytics_window.geometry("600x400")
        
        main_frame = ttk.Frame(analytics_window, padding=20)
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        ttk.Label(main_frame, text="=== Task Analytics ===", font=('Arial', 16, 'bold')).pack(pady=10)
        
        # Overall stats
        stats_text = f"""
Total Tasks: {analytics['total']}
Completed: {analytics['completed']} ({analytics['completion_rate']:.1f}%)
Pending: {analytics['pending']}
Overdue: {analytics['overdue']}
Due Today: {analytics['due_today']}
Total Pomodoros: {analytics['total_pomodoros']}
        """
        
        ttk.Label(main_frame, text=stats_text, justify=tk.LEFT).pack(pady=10)
        
        # By priority
        ttk.Label(main_frame, text="\nBy Priority:", font=('Arial', 12, 'bold')).pack()
        priority_text = "\n".join([f"  {k}: {v}" for k, v in analytics['by_priority'].items()])
        ttk.Label(main_frame, text=priority_text, justify=tk.LEFT).pack()
        
        ttk.Button(main_frame, text="Close", command=analytics_window.destroy).pack(pady=20)
    
    def _open_pomodoro_timer(self):
        """Open Pomodoro timer window."""
        if not self.selected_task_id:
            messagebox.showwarning("Warning", "Please select a task first")
            return
        
        timer_window = tk.Toplevel(self.root)
        timer_window.title("Pomodoro Timer")
        timer_window.geometry("400x300")
        
        self.pomodoro_time = 25 * 60  # 25 minutes in seconds
        self.pomodoro_running = False
        
        main_frame = ttk.Frame(timer_window, padding=20)
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        ttk.Label(main_frame, text=f"Task ID: {self.selected_task_id}", font=('Arial', 12)).pack()
        
        self.timer_label = ttk.Label(main_frame, text="25:00", font=('Arial', 48, 'bold'))
        self.timer_label.pack(pady=20)
        
        button_frame = ttk.Frame(main_frame)
        button_frame.pack()
        
        def start_timer():
            self.pomodoro_running = True
            self._countdown(timer_window)
        
        def stop_timer():
            self.pomodoro_running = False
        
        ttk.Button(button_frame, text="Start", command=start_timer).pack(side=tk.LEFT, padx=5)
        ttk.Button(button_frame, text="Stop", command=stop_timer).pack(side=tk.LEFT, padx=5)
        ttk.Button(button_frame, text="Complete & Log", 
                   command=lambda: self._complete_pomodoro(timer_window)).pack(side=tk.LEFT, padx=5)
    
    def _countdown(self, window):
        """Countdown timer for Pomodoro."""
        if self.pomodoro_running and self.pomodoro_time > 0:
            minutes = self.pomodoro_time // 60
            seconds = self.pomodoro_time % 60
            time_str = f"{minutes:02d}:{seconds:02d}"
            self.timer_label.config(text=time_str)
            self.pomodoro_time -= 1
            window.after(1000, lambda: self._countdown(window))
        elif self.pomodoro_time == 0:
            self.timer_label.config(text="00:00")
            messagebox.showinfo("Pomodoro Complete", "Time's up! Take a break.")
    
    def _complete_pomodoro(self, window):
        """Complete and log Pomodoro session."""
        self.storage.log_pomodoro_session(self.selected_task_id)
        window.destroy()
        task = self.storage.get_task(self.selected_task_id)
        self._display_task_details(task)
        self.status_label.config(text="Pomodoro session logged")
    
    def _show_about(self):
        """Show about dialog."""
        messagebox.showinfo("About", 
            "Task Manager v2.0\n\n"
            "Generated by OpenClaw Agent\n\n"
            "Features:\n"
            "- Task management with priorities\n"
            "- Tags and sub-tasks\n"
            "- Repeating tasks\n"
            "- Pomodoro timer\n"
            "- Analytics and backups\n"
            "- GUI and CLI interfaces")


class AddTaskDialog:
    """Dialog for adding a new task."""
    
    def __init__(self, parent, tags: List[Tag]):
        self.result = None
        
        self.dialog = tk.Toplevel(parent)
        self.dialog.title("Add Task")
        self.dialog.geometry("500x600")
        self.dialog.transient(parent)
        self.dialog.grab_set()
        
        main_frame = ttk.Frame(self.dialog, padding=20)
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        # Title
        ttk.Label(main_frame, text="Title:").grid(row=0, column=0, sticky=tk.W, pady=5)
        self.title_entry = ttk.Entry(main_frame, width=40)
        self.title_entry.grid(row=0, column=1, pady=5)
        
        # Description
        ttk.Label(main_frame, text="Description:").grid(row=1, column=0, sticky=tk.NW, pady=5)
        self.desc_text = tk.Text(main_frame, width=40, height=5)
        self.desc_text.grid(row=1, column=1, pady=5)
        
        # Priority
        ttk.Label(main_frame, text="Priority:").grid(row=2, column=0, sticky=tk.W, pady=5)
        self.priority_var = tk.StringVar(value="MEDIUM")
        priority_combo = ttk.Combobox(main_frame, textvariable=self.priority_var, 
                                       values=["LOW", "MEDIUM", "HIGH", "CRITICAL"])
        priority_combo.grid(row=2, column=1, pady=5)
        
        # Due date
        ttk.Label(main_frame, text="Due Date (YYYY-MM-DD):").grid(row=3, column=0, sticky=tk.W, pady=5)
        self.due_date_entry = ttk.Entry(main_frame, width=20)
        self.due_date_entry.grid(row=3, column=1, sticky=tk.W, pady=5)
        
        # Reminder date
        ttk.Label(main_frame, text="Reminder (YYYY-MM-DD HH:MM):").grid(row=4, column=0, sticky=tk.W, pady=5)
        self.reminder_entry = ttk.Entry(main_frame, width=20)
        self.reminder_entry.grid(row=4, column=1, sticky=tk.W, pady=5)
        
        # Repeat frequency
        ttk.Label(main_frame, text="Repeat:").grid(row=5, column=0, sticky=tk.W, pady=5)
        self.repeat_var = tk.StringVar(value="NONE")
        repeat_combo = ttk.Combobox(main_frame, textvariable=self.repeat_var,
                                     values=["NONE", "DAILY", "WEEKLY", "MONTHLY", "YEARLY"])
        repeat_combo.grid(row=5, column=1, pady=5)
        
        # Tags (simplified - enter tag IDs)
        ttk.Label(main_frame, text="Tags (comma-separated IDs):").grid(row=6, column=0, sticky=tk.W, pady=5)
        self.tags_entry = ttk.Entry(main_frame, width=20)
        self.tags_entry.grid(row=6, column=1, sticky=tk.W, pady=5)
        
        # Buttons
        button_frame = ttk.Frame(main_frame)
        button_frame.grid(row=7, column=0, columnspan=2, pady=20)
        
        ttk.Button(button_frame, text="OK", command=self._ok).pack(side=tk.LEFT, padx=5)
        ttk.Button(button_frame, text="Cancel", command=self.dialog.destroy).pack(side=tk.LEFT, padx=5)
        
        self.dialog.wait_window()
    
    def _ok(self):
        """Process OK button."""
        try:
            title = self.title_entry.get().strip()
            if not title:
                messagebox.showwarning("Warning", "Title is required")
                return
            
            description = self.desc_text.get('1.0', tk.END).strip()
            priority = Priority[self.priority_var.get()]
            
            due_date = None
            if self.due_date_entry.get().strip():
                due_date = datetime.strptime(self.due_date_entry.get(), '%Y-%m-%d')
            
            reminder_date = None
            if self.reminder_entry.get().strip():
                reminder_date = datetime.strptime(self.reminder_entry.get(), '%Y-%m-%d %H:%M')
            
            repeat_frequency = RepeatFrequency[self.repeat_var.get()]
            
            tags = []
            if self.tags_entry.get().strip():
                tags = [int(t.strip()) for t in self.tags_entry.get().split(',')]
            
            self.result = {
                'title': title,
                'description': description,
                'priority': priority,
                'due_date': due_date,
                'reminder_date': reminder_date,
                'repeat_frequency': repeat_frequency,
                'tags': tags
            }
            
            self.dialog.destroy()
        
        except Exception as e:
            messagebox.showerror("Error", str(e))


class EditTaskDialog:
    """Dialog for editing a task."""
    
    def __init__(self, parent, task: Task, tags: List[Tag]):
        self.result = None
        
        self.dialog = tk.Toplevel(parent)
        self.dialog.title("Edit Task")
        self.dialog.geometry("500x650")
        self.dialog.transient(parent)
        self.dialog.grab_set()
        
        main_frame = ttk.Frame(self.dialog, padding=20)
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        # Title
        ttk.Label(main_frame, text="Title:").grid(row=0, column=0, sticky=tk.W, pady=5)
        self.title_entry = ttk.Entry(main_frame, width=40)
        self.title_entry.insert(0, task.title)
        self.title_entry.grid(row=0, column=1, pady=5)
        
        # Description
        ttk.Label(main_frame, text="Description:").grid(row=1, column=0, sticky=tk.NW, pady=5)
        self.desc_text = tk.Text(main_frame, width=40, height=5)
        self.desc_text.insert('1.0', task.description)
        self.desc_text.grid(row=1, column=1, pady=5)
        
        # Priority
        ttk.Label(main_frame, text="Priority:").grid(row=2, column=0, sticky=tk.W, pady=5)
        self.priority_var = tk.StringVar(value=task.priority.name)
        priority_combo = ttk.Combobox(main_frame, textvariable=self.priority_var,
                                       values=["LOW", "MEDIUM", "HIGH", "CRITICAL"])
        priority_combo.grid(row=2, column=1, pady=5)
        
        # Due date
        ttk.Label(main_frame, text="Due Date (YYYY-MM-DD):").grid(row=3, column=0, sticky=tk.W, pady=5)
        self.due_date_entry = ttk.Entry(main_frame, width=20)
        if task.due_date:
            self.due_date_entry.insert(0, task.due_date.strftime('%Y-%m-%d'))
        self.due_date_entry.grid(row=3, column=1, sticky=tk.W, pady=5)
        
        # Reminder date
        ttk.Label(main_frame, text="Reminder (YYYY-MM-DD HH:MM):").grid(row=4, column=0, sticky=tk.W, pady=5)
        self.reminder_entry = ttk.Entry(main_frame, width=20)
        if task.reminder_date:
            self.reminder_entry.insert(0, task.reminder_date.strftime('%Y-%m-%d %H:%M'))
        self.reminder_entry.grid(row=4, column=1, sticky=tk.W, pady=5)
        
        # Repeat frequency
        ttk.Label(main_frame, text="Repeat:").grid(row=5, column=0, sticky=tk.W, pady=5)
        self.repeat_var = tk.StringVar(value=task.repeat_frequency.name)
        repeat_combo = ttk.Combobox(main_frame, textvariable=self.repeat_var,
                                     values=["NONE", "DAILY", "WEEKLY", "MONTHLY", "YEARLY"])
        repeat_combo.grid(row=5, column=1, pady=5)
        
        # Estimated pomodoros
        ttk.Label(main_frame, text="Est. Pomodoros:").grid(row=6, column=0, sticky=tk.W, pady=5)
        self.pomodoro_entry = ttk.Spinbox(main_frame, from_=1, to=20, width=10)
        self.pomodoro_entry.set(task.estimated_pomodoros)
        self.pomodoro_entry.grid(row=6, column=1, sticky=tk.W, pady=5)
        
        # Tags
        ttk.Label(main_frame, text="Tags (comma-separated IDs):").grid(row=7, column=0, sticky=tk.W, pady=5)
        self.tags_entry = ttk.Entry(main_frame, width=20)
        self.tags_entry.insert(0, ", ".join(map(str, task.tags)))
        self.tags_entry.grid(row=7, column=1, sticky=tk.W, pady=5)
        
        # Buttons
        button_frame = ttk.Frame(main_frame)
        button_frame.grid(row=8, column=0, columnspan=2, pady=20)
        
        ttk.Button(button_frame, text="OK", command=self._ok).pack(side=tk.LEFT, padx=5)
        ttk.Button(button_frame, text="Cancel", command=self.dialog.destroy).pack(side=tk.LEFT, padx=5)
        
        self.dialog.wait_window()
    
    def _ok(self):
        """Process OK button."""
        try:
            title = self.title_entry.get().strip()
            if not title:
                messagebox.showwarning("Warning", "Title is required")
                return
            
            description = self.desc_text.get('1.0', tk.END).strip()
            priority = Priority[self.priority_var.get()]
            
            due_date = None
            if self.due_date_entry.get().strip():
                due_date = datetime.strptime(self.due_date_entry.get(), '%Y-%m-%d')
            
            reminder_date = None
            if self.reminder_entry.get().strip():
                reminder_date = datetime.strptime(self.reminder_entry.get(), '%Y-%m-%d %H:%M')
            
            repeat_frequency = RepeatFrequency[self.repeat_var.get()]
            estimated_pomodoros = int(self.pomodoro_entry.get())
            
            tags = []
            if self.tags_entry.get().strip():
                tags = [int(t.strip()) for t in self.tags_entry.get().split(',')]
            
            self.result = {
                'title': title,
                'description': description,
                'priority': priority,
                'due_date': due_date,
                'reminder_date': reminder_date,
                'repeat_frequency': repeat_frequency,
                'estimated_pomodoros': estimated_pomodoros,
                'tags': tags
            }
            
            self.dialog.destroy()
        
        except Exception as e:
            messagebox.showerror("Error", str(e))


class ManageTagsDialog:
    """Dialog for managing tags."""
    
    def __init__(self, parent, storage: TaskStorage):
        self.refresh_needed = False
        
        self.dialog = tk.Toplevel(parent)
        self.dialog.title("Manage Tags")
        self.dialog.geometry("400x400")
        self.dialog.transient(parent)
        self.dialog.grab_set()
        
        self.storage = storage
        
        main_frame = ttk.Frame(self.dialog, padding=20)
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        # Tag list
        ttk.Label(main_frame, text="Existing Tags:").pack(anchor=tk.W)
        
        self.tag_listbox = tk.Listbox(main_frame, height=10)
        self.tag_listbox.pack(fill=tk.BOTH, expand=True, pady=5)
        
        self._load_tags()
        
        # Buttons
        button_frame = ttk.Frame(main_frame)
        button_frame.pack(fill=tk.X, pady=10)
        
        ttk.Button(button_frame, text="Add", command=self._add_tag).pack(side=tk.LEFT, padx=2)
        ttk.Button(button_frame, text="Delete", command=self._delete_tag).pack(side=tk.LEFT, padx=2)
        ttk.Button(button_frame, text="Close", command=self.dialog.destroy).pack(side=tk.RIGHT, padx=2)
        
        self.dialog.wait_window()
    
    def _load_tags(self):
        """Load tags into listbox."""
        self.tag_listbox.delete(0, tk.END)
        tags = self.storage.get_all_tags()
        for tag in tags:
            self.tag_listbox.insert(tk.END, f"{tag.id}: {tag.name} ({tag.color})")
    
    def _add_tag(self):
        """Add a new tag."""
        name = simpledialog.askstring("Add Tag", "Enter tag name:")
        if not name:
            return
        
        color = colorchooser.askcolor(title="Choose tag color")[1] or "#FFFFFF"
        
        self.storage.add_tag(name, color)
        self._load_tags()
        self.refresh_needed = True
    
    def _delete_tag(self):
        """Delete selected tag."""
        selection = self.tag_listbox.curselection()
        if not selection:
            messagebox.showwarning("Warning", "Please select a tag")
            return
        
        tag_info = self.tag_listbox.get(selection[0])
        tag_id = int(tag_info.split(':')[0])
        
        if messagebox.askyesno("Confirm", "Delete this tag?"):
            self.storage.delete_tag(tag_id)
            self._load_tags()
            self.refresh_needed = True


def run_gui():
    """Run the Task Manager GUI."""
    root = tk.Tk()
    app = TaskManagerGUI(root)
    root.mainloop()


if __name__ == '__main__':
    run_gui()
