"""
Task Manager - OPENCLAW Autonomous Agent Project
Main entry point
Generated by OpenClaw Agent
"""

import sys
from pathlib import Path

# Add the current directory to the path for imports
sys.path.insert(0, str(Path(__file__).parent))

from cli import cli


if __name__ == '__main__':
    cli()