"""
Task Manager - OPENCLAW Autonomous Agent Project
Models for task management with advanced features
Generated by OpenClaw Agent
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Optional, List


class Priority(Enum):
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4


class RepeatFrequency(Enum):
    NONE = 0
    DAILY = 1
    WEEKLY = 2
    MONTHLY = 3
    YEARLY = 4


@dataclass
class Tag:
    """Represents a tag for categorizing tasks."""
    id: int
    name: str
    color: str = "#FFFFFF"  # Hex color code
    
    def __str__(self):
        return f"#{self.name}"


@dataclass
class SubTask:
    """Represents a sub-task within a main task."""
    id: int
    parent_task_id: int
    title: str
    completed: bool = False
    created_at: datetime = field(default_factory=datetime.now)


@dataclass
class Task:
    """Represents a task in the system with advanced features."""
    
    id: int
    title: str
    description: str = ""
    priority: Priority = Priority.MEDIUM
    due_date: Optional[datetime] = None
    reminder_date: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.now)
    completed: bool = False
    completed_at: Optional[datetime] = None
    
    # Advanced features
    tags: List[int] = field(default_factory=list)  # List of tag IDs
    repeat_frequency: RepeatFrequency = RepeatFrequency.NONE
    next_repeat_date: Optional[datetime] = None
    sub_tasks: List[SubTask] = field(default_factory=list)
    reminder_enabled: bool = False
    
    # Pomodoro tracking
    pomodoros_completed: int = 0
    estimated_pomodoros: int = 1
    
    def mark_complete(self):
        """Mark the task as complete."""
        self.completed = True
        self.completed_at = datetime.now()
    
    def add_subtask(self, title: str) -> SubTask:
        """Add a sub-task to this task."""
        subtask = SubTask(
            id=len(self.sub_tasks) + 1,
            parent_task_id=self.id,
            title=title
        )
        self.sub_tasks.append(subtask)
        return subtask
    
    def complete_subtask(self, subtask_id: int):
        """Mark a sub-task as complete."""
        for subtask in self.sub_tasks:
            if subtask.id == subtask_id:
                subtask.completed = True
                break
    
    def get_subtask_completion(self) -> float:
        """Get the completion percentage of sub-tasks."""
        if not self.sub_tasks:
            return 100.0
        completed = sum(1 for st in self.sub_tasks if st.completed)
        return (completed / len(self.sub_tasks)) * 100
    
    def add_pomodoro(self):
        """Increment the pomodoro count."""
        self.pomodoros_completed += 1
    
    def is_repeating_due(self) -> bool:
        """Check if a repeating task is due for regeneration."""
        if self.repeat_frequency == RepeatFrequency.NONE or not self.next_repeat_date:
            return False
        return datetime.now() >= self.next_repeat_date
    
    def regenerate_if_repeating(self) -> Optional['Task']:
        """Create a new instance of this task if it's repeating."""
        if not self.is_repeating_due():
            return None
        
        new_task = Task(
            id=0,  # Will be set by database
            title=self.title,
            description=self.description,
            priority=self.priority,
            due_date=self._calculate_next_due(),
            reminder_date=self._calculate_next_reminder(),
            repeat_frequency=self.repeat_frequency,
            next_repeat_date=self._calculate_next_repeat_date(),
            tags=self.tags.copy(),
            estimated_pomodoros=self.estimated_pomodoros
        )
        return new_task
    
    def _calculate_next_due(self) -> Optional[datetime]:
        """Calculate the next due date based on repeat frequency."""
        if not self.due_date:
            return None
        
        if self.repeat_frequency == RepeatFrequency.DAILY:
            return self.due_date + timedelta(days=1)
        elif self.repeat_frequency == RepeatFrequency.WEEKLY:
            return self.due_date + timedelta(weeks=1)
        elif self.repeat_frequency == RepeatFrequency.MONTHLY:
            return self.due_date + timedelta(days=30)
        elif self.repeat_frequency == RepeatFrequency.YEARLY:
            return self.due_date + timedelta(days=365)
        return None
    
    def _calculate_next_reminder(self) -> Optional[datetime]:
        """Calculate the next reminder date based on repeat frequency."""
        if not self.reminder_date:
            return None
        
        if self.repeat_frequency == RepeatFrequency.DAILY:
            return self.reminder_date + timedelta(days=1)
        elif self.repeat_frequency == RepeatFrequency.WEEKLY:
            return self.reminder_date + timedelta(weeks=1)
        elif self.repeat_frequency == RepeatFrequency.MONTHLY:
            return self.reminder_date + timedelta(days=30)
        elif self.repeat_frequency == RepeatFrequency.YEARLY:
            return self.reminder_date + timedelta(days=365)
        return None
    
    def _calculate_next_repeat_date(self) -> Optional[datetime]:
        """Calculate the next repeat date."""
        if self.repeat_frequency == RepeatFrequency.NONE:
            return None
        
        base_date = self.next_repeat_date or datetime.now()
        
        if self.repeat_frequency == RepeatFrequency.DAILY:
            return base_date + timedelta(days=1)
        elif self.repeat_frequency == RepeatFrequency.WEEKLY:
            return base_date + timedelta(weeks=1)
        elif self.repeat_frequency == RepeatFrequency.MONTHLY:
            return base_date + timedelta(days=30)
        elif self.repeat_frequency == RepeatFrequency.YEARLY:
            return base_date + timedelta(days=365)
        return None
    
    def __str__(self):
        status = "✓" if self.completed else "○"
        priority_icon = {
            Priority.LOW: "⊙",
            Priority.MEDIUM: "◐",
            Priority.HIGH: "◉",
            Priority.CRITICAL: "◈"
        }.get(self.priority, "○")
        
        repeat_icon = "🔄" if self.repeat_frequency != RepeatFrequency.NONE else ""
        tag_str = " ".join([f"#{i}" for i in self.tags[:3]])  # Show first 3 tags
        
        return f"[{status}] {priority_icon} {repeat_icon} {self.title} {tag_str}"