"""
Task Manager - OPENCLAW Autonomous Agent Project
Models for task management
Generated by OpenClaw Agent
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class Priority(Enum):
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4


@dataclass
class Task:
    """Represents a task in the system."""
    
    id: int
    title: str
    description: str = ""
    priority: Priority = Priority.MEDIUM
    due_date: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.now)
    completed: bool = False
    completed_at: Optional[datetime] = None
    
    def mark_complete(self):
        """Mark the task as complete."""
        self.completed = True
        self.completed_at = datetime.now()
    
    def __str__(self):
        status = "✓" if self.completed else "○"
        priority_icon = {
            Priority.LOW: "⊙",
            Priority.MEDIUM: "◐",
            Priority.HIGH: "◉",
            Priority.CRITICAL: "◈"
        }.get(self.priority, "○")
        
        return f"[{status}] {priority_icon} {self.title}"