"""
Task Manager - OPENCLAW Autonomous Agent Project
Storage layer using SQLite
Generated by OpenClaw Agent
"""

import sqlite3
from datetime import datetime
from typing import List, Optional
from pathlib import Path

from models import Task, Priority


class TaskStorage:
    """Handles persistent storage of tasks using SQLite."""
    
    def __init__(self, db_path: str = "tasks.db"):
        self.db_path = db_path
        self._init_db()
    
    def _init_db(self):
        """Initialize the database schema."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS tasks (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT NOT NULL,
                    description TEXT,
                    priority INTEGER DEFAULT 2,
                    due_date TEXT,
                    created_at TEXT NOT NULL,
                    completed INTEGER DEFAULT 0,
                    completed_at TEXT
                )
            """)
            conn.commit()
    
    def _task_from_row(self, row) -> Task:
        """Convert a database row to a Task object."""
        return Task(
            id=row[0],
            title=row[1],
            description=row[2] or "",
            priority=Priority(row[3]),
            due_date=datetime.fromisoformat(row[4]) if row[4] else None,
            created_at=datetime.fromisoformat(row[5]),
            completed=bool(row[6]),
            completed_at=datetime.fromisoformat(row[7]) if row[7] else None
        )
    
    def add_task(self, task: Task) -> int:
        """Add a new task to the database. Returns the task ID."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                INSERT INTO tasks (title, description, priority, due_date, created_at, completed)
                VALUES (?, ?, ?, ?, ?, ?)
            """, (
                task.title,
                task.description,
                task.priority.value,
                task.due_date.isoformat() if task.due_date else None,
                task.created_at.isoformat(),
                1 if task.completed else 0
            ))
            conn.commit()
            return cursor.lastrowid
    
    def get_task(self, task_id: int) -> Optional[Task]:
        """Get a task by ID."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("SELECT * FROM tasks WHERE id = ?", (task_id,))
            row = cursor.fetchone()
            return self._task_from_row(row) if row else None
    
    def get_all_tasks(self) -> List[Task]:
        """Get all tasks."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("SELECT * FROM tasks ORDER BY created_at DESC")
            return [self._task_from_row(row) for row in cursor.fetchall()]
    
    def get_pending_tasks(self) -> List[Task]:
        """Get all incomplete tasks."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("SELECT * FROM tasks WHERE completed = 0 ORDER BY priority DESC, created_at ASC")
            return [self._task_from_row(row) for row in cursor.fetchall()]
    
    def update_task(self, task: Task):
        """Update an existing task."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                UPDATE tasks SET
                    title = ?,
                    description = ?,
                    priority = ?,
                    due_date = ?,
                    completed = ?,
                    completed_at = ?
                WHERE id = ?
            """, (
                task.title,
                task.description,
                task.priority.value,
                task.due_date.isoformat() if task.due_date else None,
                1 if task.completed else 0,
                task.completed_at.isoformat() if task.completed_at else None,
                task.id
            ))
            conn.commit()
    
    def delete_task(self, task_id: int):
        """Delete a task by ID."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("DELETE FROM tasks WHERE id = ?", (task_id,))
            conn.commit()
    
    def search_tasks(self, query: str) -> List[Task]:
        """Search tasks by title or description."""
        search_term = f"%{query}%"
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT * FROM tasks 
                WHERE title LIKE ? OR description LIKE ?
                ORDER BY created_at DESC
            """, (search_term, search_term))
            return [self._task_from_row(row) for row in cursor.fetchall()]