"""
Task Manager - OPENCLAW Autonomous Agent Project
Storage layer using SQLite with advanced features
Generated by OpenClaw Agent
"""

import sqlite3
import json
from datetime import datetime, timedelta
from typing import List, Optional
from pathlib import Path

from models import Task, Priority, RepeatFrequency, SubTask, Tag


class TaskStorage:
    """Handles persistent storage of tasks using SQLite with advanced features."""
    
    def __init__(self, db_path: str = "tasks.db"):
        self.db_path = db_path
        self._init_db()
        self._add_reminder_enabled_column()
    
    def _add_reminder_enabled_column(self):
        """Add reminder_enabled column if it doesn't exist."""
        with sqlite3.connect(self.db_path) as conn:
            try:
                conn.execute("ALTER TABLE tasks ADD COLUMN reminder_enabled INTEGER DEFAULT 0")
                conn.commit()
            except sqlite3.OperationalError:
                # Column already exists
                pass
    
    def _init_db(self):
        """Initialize the database schema with all tables."""
        with sqlite3.connect(self.db_path) as conn:
            # Tasks table with advanced features
            conn.execute("""
                CREATE TABLE IF NOT EXISTS tasks (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT NOT NULL,
                    description TEXT,
                    priority INTEGER DEFAULT 2,
                    due_date TEXT,
                    reminder_date TEXT,
                    created_at TEXT NOT NULL,
                    completed INTEGER DEFAULT 0,
                    completed_at TEXT,
                    tags TEXT DEFAULT '[]',
                    repeat_frequency INTEGER DEFAULT 0,
                    next_repeat_date TEXT,
                    pomodoros_completed INTEGER DEFAULT 0,
                    estimated_pomodoros INTEGER DEFAULT 1
                )
            """)
            
            # Tags table
            conn.execute("""
                CREATE TABLE IF NOT EXISTS tags (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL UNIQUE,
                    color TEXT DEFAULT '#FFFFFF'
                )
            """)
            
            # Sub-tasks table
            conn.execute("""
                CREATE TABLE IF NOT EXISTS sub_tasks (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    parent_task_id INTEGER NOT NULL,
                    title TEXT NOT NULL,
                    completed INTEGER DEFAULT 0,
                    created_at TEXT NOT NULL,
                    FOREIGN KEY (parent_task_id) REFERENCES tasks(id) ON DELETE CASCADE
                )
            """)
            
            # Pomodoro sessions table
            conn.execute("""
                CREATE TABLE IF NOT EXISTS pomodoro_sessions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    task_id INTEGER NOT NULL,
                    duration_minutes INTEGER DEFAULT 25,
                    completed INTEGER DEFAULT 0,
                    started_at TEXT NOT NULL,
                    completed_at TEXT,
                    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
                )
            """)
            
            # Reminders table
            conn.execute("""
                CREATE TABLE IF NOT EXISTS reminders (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    task_id INTEGER NOT NULL,
                    reminder_time TEXT NOT NULL,
                    notified INTEGER DEFAULT 0,
                    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
                )
            """)
            
            # Backup metadata table
            conn.execute("""
                CREATE TABLE IF NOT EXISTS backups (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    backup_path TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    task_count INTEGER DEFAULT 0
                )
            """)
            
            conn.commit()
    
    def _task_from_row(self, row) -> Task:
        """Convert a database row to a Task object."""
        task = Task(
            id=row[0],
            title=row[1],
            description=row[2] or "",
            priority=Priority(row[3]),
            due_date=datetime.fromisoformat(row[4]) if row[4] else None,
            reminder_date=datetime.fromisoformat(row[5]) if row[5] else None,
            created_at=datetime.fromisoformat(row[6]),
            completed=bool(row[7]),
            completed_at=datetime.fromisoformat(row[8]) if row[8] else None,
            tags=json.loads(row[9]) if row[9] else [],
            repeat_frequency=RepeatFrequency(row[10]),
            next_repeat_date=datetime.fromisoformat(row[11]) if row[11] else None,
            pomodoros_completed=row[12] or 0,
            estimated_pomodoros=row[13] or 1
        )
        
        # Load sub-tasks
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                "SELECT * FROM sub_tasks WHERE parent_task_id = ?", 
                (task.id,)
            )
            task.sub_tasks = [
                SubTask(
                    id=sub[0],
                    parent_task_id=sub[1],
                    title=sub[2],
                    completed=bool(sub[3]),
                    created_at=datetime.fromisoformat(sub[4])
                )
                for sub in cursor.fetchall()
            ]
        
        return task
    
    def add_task(self, task: Task) -> int:
        """Add a new task to the database. Returns the task ID."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                INSERT INTO tasks (title, description, priority, due_date, reminder_date, 
                                   created_at, completed, tags, repeat_frequency, 
                                   next_repeat_date, pomodoros_completed, estimated_pomodoros)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                task.title,
                task.description,
                task.priority.value,
                task.due_date.isoformat() if task.due_date else None,
                task.reminder_date.isoformat() if task.reminder_date else None,
                task.created_at.isoformat(),
                1 if task.completed else 0,
                json.dumps(task.tags),
                task.repeat_frequency.value,
                task.next_repeat_date.isoformat() if task.next_repeat_date else None,
                task.pomodoros_completed,
                task.estimated_pomodoros
            ))
            task_id = cursor.lastrowid
            
            # Add sub-tasks
            for subtask in task.sub_tasks:
                conn.execute("""
                    INSERT INTO sub_tasks (parent_task_id, title, completed, created_at)
                    VALUES (?, ?, ?, ?)
                """, (task_id, subtask.title, 1 if subtask.completed else 0, 
                      subtask.created_at.isoformat()))
            
            conn.commit()
            return task_id
    
    def get_task(self, task_id: int) -> Optional[Task]:
        """Get a task by ID."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("SELECT * FROM tasks WHERE id = ?", (task_id,))
            row = cursor.fetchone()
            return self._task_from_row(row) if row else None
    
    def get_all_tasks(self) -> List[Task]:
        """Get all tasks."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("SELECT * FROM tasks ORDER BY created_at DESC")
            return [self._task_from_row(row) for row in cursor.fetchall()]
    
    def get_pending_tasks(self) -> List[Task]:
        """Get all incomplete tasks."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                "SELECT * FROM tasks WHERE completed = 0 ORDER BY priority DESC, created_at ASC"
            )
            return [self._task_from_row(row) for row in cursor.fetchall()]
    
    def update_task(self, task: Task):
        """Update an existing task."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                UPDATE tasks SET
                    title = ?,
                    description = ?,
                    priority = ?,
                    due_date = ?,
                    reminder_date = ?,
                    completed = ?,
                    completed_at = ?,
                    tags = ?,
                    repeat_frequency = ?,
                    next_repeat_date = ?,
                    pomodoros_completed = ?,
                    estimated_pomodoros = ?
                WHERE id = ?
            """, (
                task.title,
                task.description,
                task.priority.value,
                task.due_date.isoformat() if task.due_date else None,
                task.reminder_date.isoformat() if task.reminder_date else None,
                1 if task.completed else 0,
                task.completed_at.isoformat() if task.completed_at else None,
                json.dumps(task.tags),
                task.repeat_frequency.value,
                task.next_repeat_date.isoformat() if task.next_repeat_date else None,
                task.pomodoros_completed,
                task.estimated_pomodoros,
                task.id
            ))
            
            # Update sub-tasks (simple approach: delete and re-add)
            conn.execute("DELETE FROM sub_tasks WHERE parent_task_id = ?", (task.id,))
            for subtask in task.sub_tasks:
                conn.execute("""
                    INSERT INTO sub_tasks (parent_task_id, title, completed, created_at)
                    VALUES (?, ?, ?, ?)
                """, (task.id, subtask.title, 1 if subtask.completed else 0,
                      subtask.created_at.isoformat()))
            
            conn.commit()
    
    def delete_task(self, task_id: int):
        """Delete a task by ID."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("DELETE FROM tasks WHERE id = ?", (task_id,))
            conn.commit()
    
    def search_tasks(self, query: str) -> List[Task]:
        """Search tasks by title or description."""
        search_term = f"%{query}%"
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT * FROM tasks 
                WHERE title LIKE ? OR description LIKE ?
                ORDER BY created_at DESC
            """, (search_term, search_term))
            return [self._task_from_row(row) for row in cursor.fetchall()]
    
    def get_tasks_by_priority(self, priority: Priority) -> List[Task]:
        """Get tasks filtered by priority."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                "SELECT * FROM tasks WHERE priority = ? AND completed = 0 ORDER BY created_at",
                (priority.value,)
            )
            return [self._task_from_row(row) for row in cursor.fetchall()]
    
    def get_tasks_by_tag(self, tag_id: int) -> List[Task]:
        """Get tasks with a specific tag."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                "SELECT * FROM tasks WHERE tags LIKE ? ORDER BY created_at",
                (f'%{tag_id}%',)
            )
            return [self._task_from_row(row) for row in cursor.fetchall()]
    
    def get_repeating_tasks(self) -> List[Task]:
        """Get all repeating tasks."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                "SELECT * FROM tasks WHERE repeat_frequency > 0 AND completed = 0"
            )
            return [self._task_from_row(row) for row in cursor.fetchall()]
    
    def get_overdue_tasks(self) -> List[Task]:
        """Get tasks that are past their due date."""
        now = datetime.now().isoformat()
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT * FROM tasks 
                WHERE due_date < ? AND completed = 0 AND due_date IS NOT NULL
                ORDER BY due_date ASC
            """, (now,))
            return [self._task_from_row(row) for row in cursor.fetchall()]
    
    def get_tasks_due_today(self) -> List[Task]:
        """Get tasks due today."""
        today_start = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0).isoformat()
        today_end = datetime.now().replace(hour=23, minute=59, second=59, microsecond=999999).isoformat()
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT * FROM tasks 
                WHERE due_date >= ? AND due_date <= ? AND completed = 0
            """, (today_start, today_end))
            return [self._task_from_row(row) for row in cursor.fetchall()]
    
    def add_tag(self, name: str, color: str = "#FFFFFF") -> int:
        """Add a new tag."""
        with sqlite3.connect(self.db_path) as conn:
            try:
                cursor = conn.execute(
                    "INSERT INTO tags (name, color) VALUES (?, ?)",
                    (name, color)
                )
                conn.commit()
                return cursor.lastrowid
            except sqlite3.IntegrityError:
                # Tag already exists
                cursor = conn.execute("SELECT id FROM tags WHERE name = ?", (name,))
                return cursor.fetchone()[0]
    
    def get_tag(self, tag_id: int) -> Optional[Tag]:
        """Get a tag by ID."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("SELECT * FROM tags WHERE id = ?", (tag_id,))
            row = cursor.fetchone()
            return Tag(id=row[0], name=row[1], color=row[2]) if row else None
    
    def get_all_tags(self) -> List[Tag]:
        """Get all tags."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("SELECT * FROM tags ORDER BY name")
            return [Tag(id=row[0], name=row[1], color=row[2]) for row in cursor.fetchall()]
    
    def delete_tag(self, tag_id: int):
        """Delete a tag."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("DELETE FROM tags WHERE id = ?", (tag_id,))
            conn.commit()
    
    def add_subtask(self, task_id: int, title: str) -> int:
        """Add a sub-task to a task."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                INSERT INTO sub_tasks (parent_task_id, title, completed, created_at)
                VALUES (?, ?, 0, ?)
            """, (task_id, title, datetime.now().isoformat()))
            conn.commit()
            return cursor.lastrowid
    
    def complete_subtask(self, subtask_id: int):
        """Mark a sub-task as complete."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                "UPDATE sub_tasks SET completed = 1 WHERE id = ?",
                (subtask_id,)
            )
            conn.commit()
    
    def log_pomodoro_session(self, task_id: int, duration_minutes: int = 25):
        """Log a Pomodoro session for a task."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                INSERT INTO pomodoro_sessions (task_id, duration_minutes, completed, started_at, completed_at)
                VALUES (?, ?, 1, ?, ?)
            """, (task_id, duration_minutes, datetime.now().isoformat(), 
                  datetime.now().isoformat()))
            
            # Update task's pomodoro count
            conn.execute("""
                UPDATE tasks SET pomodoros_completed = pomodoros_completed + 1
                WHERE id = ?
            """, (task_id,))
            
            conn.commit()
    
    def get_task_analytics(self) -> dict:
        """Get comprehensive analytics for tasks."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("SELECT * FROM tasks")
            all_tasks = [self._task_from_row(row) for row in cursor.fetchall()]
        
        total = len(all_tasks)
        completed = sum(1 for t in all_tasks if t.completed)
        pending = total - completed
        
        # Priority breakdown
        priority_counts = {p.name: 0 for p in Priority}
        for task in all_tasks:
            priority_counts[task.priority.name] += 1
        
        # Repeat frequency breakdown
        repeat_counts = {rf.name: 0 for rf in RepeatFrequency}
        for task in all_tasks:
            repeat_counts[task.repeat_frequency.name] += 1
        
        # Overdue tasks
        overdue = len([t for t in all_tasks if not t.completed and t.due_date and t.due_date < datetime.now()])
        
        # Today's tasks
        today = len([t for t in all_tasks if t.due_date and 
                     t.due_date.date() == datetime.now().date()])
        
        # Total pomodoros
        total_pomodoros = sum(t.pomodoros_completed for t in all_tasks)
        
        return {
            'total': total,
            'completed': completed,
            'pending': pending,
            'completion_rate': (completed / total * 100) if total > 0 else 0,
            'by_priority': priority_counts,
            'by_repeat_frequency': repeat_counts,
            'overdue': overdue,
            'due_today': today,
            'total_pomodoros': total_pomodoros
        }
    
    def create_backup(self, backup_path: str) -> str:
        """Create a backup of the database."""
        import shutil
        from pathlib import Path
        
        backup_file = Path(backup_path) / f"tasks_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.db"
        shutil.copy2(self.db_path, backup_file)
        
        # Record backup in database
        with sqlite3.connect(self.db_path) as conn:
            task_count = conn.execute("SELECT COUNT(*) FROM tasks").fetchone()[0]
            conn.execute("""
                INSERT INTO backups (backup_path, created_at, task_count)
                VALUES (?, ?, ?)
            """, (str(backup_file), datetime.now().isoformat(), task_count))
            conn.commit()
        
        return str(backup_file)
    
    def get_backups(self) -> List[dict]:
        """Get list of backups."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("SELECT * FROM backups ORDER BY created_at DESC")
            return [
                {
                    'id': row[0],
                    'path': row[1],
                    'created_at': datetime.fromisoformat(row[2]),
                    'task_count': row[3]
                }
                for row in cursor.fetchall()
            ]