"""
Task Manager - OPENCLAW Autonomous Agent Project
Web-based Graphical User Interface using Flask
Generated by OpenClaw Agent
"""

from flask import Flask, render_template_string, request, jsonify, redirect, url_for
from datetime import datetime, timedelta
from typing import Optional, List
import json

from models import Task, Priority, RepeatFrequency, Tag, SubTask
from storage import TaskStorage

app = Flask(__name__)
storage = TaskStorage()

# HTML Template with modern CSS and JavaScript
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Manager - OPENCLAW</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 15px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }
        
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        
        .header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }
        
        .stats-bar {
            display: flex;
            justify-content: space-around;
            padding: 20px;
            background: #f8f9fa;
            border-bottom: 2px solid #e9ecef;
        }
        
        .stat-item {
            text-align: center;
        }
        
        .stat-number {
            font-size: 2em;
            font-weight: bold;
            color: #667eea;
        }
        
        .stat-label {
            color: #6c757d;
            font-size: 0.9em;
        }
        
        .main-content {
            display: flex;
            padding: 30px;
            gap: 30px;
        }
        
        .task-list-panel {
            flex: 2;
        }
        
        .task-details-panel {
            flex: 1;
            background: #f8f9fa;
            padding: 20px;
            border-radius: 10px;
        }
        
        .toolbar {
            display: flex;
            gap: 10px;
            margin-bottom: 20px;
            flex-wrap: wrap;
        }
        
        .btn {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
            transition: all 0.3s;
        }
        
        .btn-primary {
            background: #667eea;
            color: white;
        }
        
        .btn-primary:hover {
            background: #5568d3;
        }
        
        .btn-success {
            background: #28a745;
            color: white;
        }
        
        .btn-danger {
            background: #dc3545;
            color: white;
        }
        
        .btn-info {
            background: #17a2b8;
            color: white;
        }
        
        .filter-select {
            padding: 10px;
            border: 2px solid #dee2e6;
            border-radius: 5px;
            font-size: 14px;
        }
        
        .task-list {
            list-style: none;
        }
        
        .task-item {
            background: white;
            border: 2px solid #e9ecef;
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 15px;
            cursor: pointer;
            transition: all 0.3s;
        }
        
        .task-item:hover {
            border-color: #667eea;
            box-shadow: 0 5px 15px rgba(102, 126, 234, 0.2);
        }
        
        .task-item.completed {
            opacity: 0.6;
            background: #d4edda;
        }
        
        .task-item.priority-critical {
            border-left: 5px solid #dc3545;
        }
        
        .task-item.priority-high {
            border-left: 5px solid #ff9800;
        }
        
        .task-item.priority-medium {
            border-left: 5px solid #ffc107;
        }
        
        .task-item.priority-low {
            border-left: 5px solid #28a745;
        }
        
        .task-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }
        
        .task-title {
            font-size: 1.2em;
            font-weight: bold;
            color: #333;
        }
        
        .task-badge {
            padding: 5px 10px;
            border-radius: 20px;
            font-size: 0.8em;
            font-weight: bold;
        }
        
        .badge-critical {
            background: #dc3545;
            color: white;
        }
        
        .badge-high {
            background: #ff9800;
            color: white;
        }
        
        .badge-medium {
            background: #ffc107;
            color: #333;
        }
        
        .badge-low {
            background: #28a745;
            color: white;
        }
        
        .task-meta {
            display: flex;
            gap: 15px;
            color: #6c757d;
            font-size: 0.9em;
            margin-top: 10px;
        }
        
        .task-tags {
            display: flex;
            gap: 5px;
            flex-wrap: wrap;
            margin-top: 10px;
        }
        
        .tag {
            background: #e9ecef;
            padding: 3px 8px;
            border-radius: 15px;
            font-size: 0.8em;
            color: #495057;
        }
        
        .form-group {
            margin-bottom: 20px;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
            color: #333;
        }
        
        .form-control {
            width: 100%;
            padding: 10px;
            border: 2px solid #dee2e6;
            border-radius: 5px;
            font-size: 14px;
        }
        
        .form-control:focus {
            outline: none;
            border-color: #667eea;
        }
        
        .checkbox-group {
            display: flex;
            align-items: center;
            gap: 10px;
        }
        
        .modal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0,0,0,0.5);
            z-index: 1000;
        }
        
        .modal.show {
            display: flex;
            align-items: center;
            justify-content: center;
        }
        
        .modal-content {
            background: white;
            padding: 30px;
            border-radius: 10px;
            max-width: 600px;
            width: 90%;
            max-height: 90vh;
            overflow-y: auto;
        }
        
        .modal-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }
        
        .close-btn {
            font-size: 1.5em;
            cursor: pointer;
            color: #6c757d;
        }
        
        .pomodoro-timer {
            text-align: center;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-radius: 10px;
            margin-bottom: 20px;
        }
        
        .timer-display {
            font-size: 3em;
            font-weight: bold;
            margin: 20px 0;
        }
        
        .subtask-list {
            list-style: none;
            margin-top: 10px;
        }
        
        .subtask-item {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 8px 0;
            border-bottom: 1px solid #e9ecef;
        }
        
        @media (max-width: 768px) {
            .main-content {
                flex-direction: column;
            }
            
            .stats-bar {
                flex-wrap: wrap;
                gap: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚀 Task Manager - OPENCLAW</h1>
            <p>Your Personal Productivity Assistant</p>
        </div>
        
        <div class="stats-bar">
            <div class="stat-item">
                <div class="stat-number" id="total-tasks">0</div>
                <div class="stat-label">Total Tasks</div>
            </div>
            <div class="stat-item">
                <div class="stat-number" id="completed-tasks">0</div>
                <div class="stat-label">Completed</div>
            </div>
            <div class="stat-item">
                <div class="stat-number" id="pending-tasks">0</div>
                <div class="stat-label">Pending</div>
            </div>
            <div class="stat-item">
                <div class="stat-number" id="overdue-tasks">0</div>
                <div class="stat-label">Overdue</div>
            </div>
        </div>
        
        <div class="main-content">
            <div class="task-list-panel">
                <div class="toolbar">
                    <button class="btn btn-primary" onclick="openAddModal()">+ Add Task</button>
                    <select class="filter-select" id="filter-priority" onchange="loadTasks()">
                        <option value="all">All Priorities</option>
                        <option value="low">Low</option>
                        <option value="medium">Medium</option>
                        <option value="high">High</option>
                        <option value="critical">Critical</option>
                    </select>
                    <select class="filter-select" id="filter-status" onchange="loadTasks()">
                        <option value="all">All Status</option>
                        <option value="pending">Pending</option>
                        <option value="completed">Completed</option>
                        <option value="overdue">Overdue</option>
                    </select>
                    <input type="text" class="filter-select" placeholder="Search tasks..." id="search-box" onkeyup="loadTasks()">
                    <button class="btn btn-info" onclick="togglePomodoro()">🍅 Pomodoro</button>
                    <button class="btn btn-success" onclick="backupData()">💾 Backup</button>
                </div>
                
                <ul class="task-list" id="task-list">
                    <!-- Tasks will be loaded here -->
                </ul>
            </div>
            
            <div class="task-details-panel" id="task-details">
                <h3>Task Details</h3>
                <p>Select a task to view details</p>
            </div>
        </div>
    </div>
    
    <!-- Add/Edit Task Modal -->
    <div class="modal" id="task-modal">
        <div class="modal-content">
            <div class="modal-header">
                <h2 id="modal-title">Add New Task</h2>
                <span class="close-btn" onclick="closeModal()">&times;</span>
            </div>
            <form id="task-form" onsubmit="saveTask(event)">
                <input type="hidden" id="task-id">
                <div class="form-group">
                    <label>Title *</label>
                    <input type="text" class="form-control" id="task-title" required>
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" id="task-description" rows="3"></textarea>
                </div>
                <div class="form-group">
                    <label>Priority</label>
                    <select class="form-control" id="task-priority">
                        <option value="low">Low</option>
                        <option value="medium" selected>Medium</option>
                        <option value="high">High</option>
                        <option value="critical">Critical</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Due Date</label>
                    <input type="datetime-local" class="form-control" id="task-due-date">
                </div>
                <div class="form-group">
                    <label>Tags (comma-separated)</label>
                    <input type="text" class="form-control" id="task-tags" placeholder="work, urgent, personal">
                </div>
                <div class="form-group">
                    <label>Repeat Frequency</label>
                    <select class="form-control" id="task-repeat">
                        <option value="none">None</option>
                        <option value="daily">Daily</option>
                        <option value="weekly">Weekly</option>
                        <option value="monthly">Monthly</option>
                    </select>
                </div>
                <div class="form-group checkbox-group">
                    <input type="checkbox" id="task-reminder">
                    <label for="task-reminder">Enable Reminder</label>
                </div>
                <div class="form-group">
                    <label>Subtasks (one per line)</label>
                    <textarea class="form-control" id="task-subtasks" rows="3" placeholder="Subtask 1&#10;Subtask 2"></textarea>
                </div>
                <button type="submit" class="btn btn-primary" style="width: 100%;">Save Task</button>
            </form>
        </div>
    </div>
    
    <!-- Pomodoro Modal -->
    <div class="modal" id="pomodoro-modal">
        <div class="modal-content">
            <div class="modal-header">
                <h2>🍅 Pomodoro Timer</h2>
                <span class="close-btn" onclick="closePomodoro()">&times;</span>
            </div>
            <div class="pomodoro-timer">
                <div class="timer-display" id="timer-display">25:00</div>
                <button class="btn btn-success" id="start-btn" onclick="startTimer()">Start</button>
                <button class="btn btn-danger" id="pause-btn" onclick="pauseTimer()" style="display:none;">Pause</button>
                <button class="btn btn-info" onclick="resetTimer()">Reset</button>
            </div>
            <p>Focus for 25 minutes, then take a 5-minute break!</p>
        </div>
    </div>
    
    <script>
        let timerInterval;
        let timeLeft = 1500; // 25 minutes in seconds
        let isRunning = false;
        
        // Load tasks from API
        async function loadTasks() {
            const priorityFilter = document.getElementById('filter-priority').value;
            const statusFilter = document.getElementById('filter-status').value;
            const searchQuery = document.getElementById('search-box').value;
            
            try {
                const response = await fetch(`/api/tasks?priority=${priorityFilter}&status=${statusFilter}&search=${searchQuery}`);
                const data = await response.json();
                
                const taskList = document.getElementById('task-list');
                taskList.innerHTML = '';
                
                data.tasks.forEach(task => {
                    const li = document.createElement('li');
                    li.className = `task-item ${task.completed ? 'completed' : ''} priority-${task.priority}`;
                    li.onclick = () => showTaskDetails(task.id);
                    
                    const dueDate = task.due_date ? new Date(task.due_date).toLocaleDateString() : 'No due date';
                    const tags = task.tags.map(tag => `<span class="tag">${tag.name}</span>`).join('');
                    
                    li.innerHTML = `
                        <div class="task-header">
                            <span class="task-title">${task.completed ? '✅ ' : ''}${task.title}</span>
                            <span class="task-badge badge-${task.priority}">${task.priority.toUpperCase()}</span>
                        </div>
                        <p>${task.description || ''}</p>
                        <div class="task-meta">
                            <span>📅 ${dueDate}</span>
                            ${task.subtasks.length > 0 ? `<span>📋 ${task.subtasks.filter(s => s.completed).length}/${task.subtasks.length} subtasks</span>` : ''}
                        </div>
                        ${tags ? `<div class="task-tags">${tags}</div>` : ''}
                    `;
                    
                    taskList.appendChild(li);
                });
                
                updateStats(data.stats);
            } catch (error) {
                console.error('Error loading tasks:', error);
            }
        }
        
        // Update statistics
        function updateStats(stats) {
            document.getElementById('total-tasks').textContent = stats.total;
            document.getElementById('completed-tasks').textContent = stats.completed;
            document.getElementById('pending-tasks').textContent = stats.pending;
            document.getElementById('overdue-tasks').textContent = stats.overdue;
        }
        
        // Show task details
        async function showTaskDetails(taskId) {
            try {
                const response = await fetch(`/api/tasks/${taskId}`);
                const task = await response.json();
                
                const detailsPanel = document.getElementById('task-details');
                const subtasksHtml = task.subtasks.map(sub => `
                    <li class="subtask-item">
                        <input type="checkbox" ${sub.completed ? 'checked' : ''} onchange="toggleSubtask(${task.id}, ${sub.id})">
                        <span style="${sub.completed ? 'text-decoration: line-through' : ''}">${sub.title}</span>
                    </li>
                `).join('');
                
                detailsPanel.innerHTML = `
                    <h3>${task.title}</h3>
                    <p><strong>Priority:</strong> ${task.priority.toUpperCase()}</p>
                    <p><strong>Status:</strong> ${task.completed ? '✅ Completed' : '⏳ Pending'}</p>
                    <p><strong>Due:</strong> ${task.due_date ? new Date(task.due_date).toLocaleString() : 'Not set'}</p>
                    <p><strong>Description:</strong> ${task.description || 'No description'}</p>
                    <p><strong>Tags:</strong> ${task.tags.map(t => t.name).join(', ') || 'None'}</p>
                    <p><strong>Repeat:</strong> ${task.repeat_frequency || 'None'}</p>
                    <p><strong>Reminder:</strong> ${task.reminder_enabled ? 'Enabled' : 'Disabled'}</p>
                    <h4>Subtasks:</h4>
                    <ul class="subtask-list">${subtasksHtml}</ul>
                    <div style="margin-top: 20px;">
                        <button class="btn btn-success" onclick="toggleTaskComplete(${task.id})">${task.completed ? 'Mark Incomplete' : 'Mark Complete'}</button>
                        <button class="btn btn-primary" onclick="editTask(${task.id})">Edit</button>
                        <button class="btn btn-danger" onclick="deleteTask(${task.id})">Delete</button>
                    </div>
                `;
            } catch (error) {
                console.error('Error loading task details:', error);
            }
        }
        
        // Open add modal
        function openAddModal() {
            document.getElementById('modal-title').textContent = 'Add New Task';
            document.getElementById('task-form').reset();
            document.getElementById('task-id').value = '';
            document.getElementById('task-modal').classList.add('show');
        }
        
        // Close modal
        function closeModal() {
            document.getElementById('task-modal').classList.remove('show');
        }
        
        // Save task
        async function saveTask(event) {
            event.preventDefault();
            
            const taskId = document.getElementById('task-id').value;
            const taskData = {
                title: document.getElementById('task-title').value,
                description: document.getElementById('task-description').value,
                priority: document.getElementById('task-priority').value,
                due_date: document.getElementById('task-due-date').value || null,
                tags: document.getElementById('task-tags').value.split(',').map(t => t.trim()).filter(t => t),
                repeat_frequency: document.getElementById('task-repeat').value !== 'none' ? document.getElementById('task-repeat').value : null,
                reminder_enabled: document.getElementById('task-reminder').checked,
                subtasks: document.getElementById('task-subtasks').value.split('\\n').map(s => s.trim()).filter(s => s)
            };
            
            try {
                const url = taskId ? `/api/tasks/${taskId}` : '/api/tasks';
                const method = taskId ? 'PUT' : 'POST';
                
                const response = await fetch(url, {
                    method: method,
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(taskData)
                });
                
                if (response.ok) {
                    closeModal();
                    loadTasks();
                } else {
                    alert('Error saving task');
                }
            } catch (error) {
                console.error('Error saving task:', error);
            }
        }
        
        // Edit task
        async function editTask(taskId) {
            try {
                const response = await fetch(`/api/tasks/${taskId}`);
                const task = await response.json();
                
                document.getElementById('modal-title').textContent = 'Edit Task';
                document.getElementById('task-id').value = task.id;
                document.getElementById('task-title').value = task.title;
                document.getElementById('task-description').value = task.description || '';
                document.getElementById('task-priority').value = task.priority;
                document.getElementById('task-due-date').value = task.due_date ? task.due_date.slice(0, 16) : '';
                document.getElementById('task-tags').value = task.tags.map(t => t.name).join(', ');
                document.getElementById('task-repeat').value = task.repeat_frequency || 'none';
                document.getElementById('task-reminder').checked = task.reminder_enabled;
                document.getElementById('task-subtasks').value = task.subtasks.map(s => s.title).join('\\n');
                
                document.getElementById('task-modal').classList.add('show');
            } catch (error) {
                console.error('Error loading task for edit:', error);
            }
        }
        
        // Delete task
        async function deleteTask(taskId) {
            if (confirm('Are you sure you want to delete this task?')) {
                try {
                    const response = await fetch(`/api/tasks/${taskId}`, { method: 'DELETE' });
                    if (response.ok) {
                        loadTasks();
                        document.getElementById('task-details').innerHTML = '<h3>Task Details</h3><p>Select a task to view details</p>';
                    }
                } catch (error) {
                    console.error('Error deleting task:', error);
                }
            }
        }
        
        // Toggle task completion
        async function toggleTaskComplete(taskId) {
            try {
                const response = await fetch(`/api/tasks/${taskId}/toggle`, { method: 'POST' });
                if (response.ok) {
                    loadTasks();
                    showTaskDetails(taskId);
                }
            } catch (error) {
                console.error('Error toggling task:', error);
            }
        }
        
        // Toggle subtask completion
        async function toggleSubtask(taskId, subtaskId) {
            try {
                const response = await fetch(`/api/tasks/${taskId}/subtasks/${subtaskId}/toggle`, { method: 'POST' });
                if (response.ok) {
                    showTaskDetails(taskId);
                }
            } catch (error) {
                console.error('Error toggling subtask:', error);
            }
        }
        
        // Toggle Pomodoro modal
        function togglePomodoro() {
            document.getElementById('pomodoro-modal').classList.add('show');
        }
        
        // Close Pomodoro modal
        function closePomodoro() {
            document.getElementById('pomodoro-modal').classList.remove('show');
            pauseTimer();
        }
        
        // Timer functions
        function startTimer() {
            if (!isRunning) {
                isRunning = true;
                document.getElementById('start-btn').style.display = 'none';
                document.getElementById('pause-btn').style.display = 'inline-block';
                
                timerInterval = setInterval(() => {
                    timeLeft--;
                    updateTimerDisplay();
                    
                    if (timeLeft <= 0) {
                        clearInterval(timerInterval);
                        alert('Pomodoro session complete! Take a break.');
                        resetTimer();
                    }
                }, 1000);
            }
        }
        
        function pauseTimer() {
            isRunning = false;
            clearInterval(timerInterval);
            document.getElementById('start-btn').style.display = 'inline-block';
            document.getElementById('pause-btn').style.display = 'none';
        }
        
        function resetTimer() {
            pauseTimer();
            timeLeft = 1500;
            updateTimerDisplay();
        }
        
        function updateTimerDisplay() {
            const minutes = Math.floor(timeLeft / 60);
            const seconds = timeLeft % 60;
            document.getElementById('timer-display').textContent = 
                `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
        }
        
        // Backup data
        async function backupData() {
            try {
                const response = await fetch('/api/backup');
                const blob = await response.blob();
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `task_backup_${new Date().toISOString().split('T')[0]}.json`;
                a.click();
            } catch (error) {
                console.error('Error backing up data:', error);
            }
        }
        
        // Load tasks on page load
        loadTasks();
    </script>
</body>
</html>
"""

@app.route('/')
def index():
    return render_template_string(HTML_TEMPLATE)

@app.route('/api/tasks', methods=['GET'])
def get_tasks():
    priority_filter = request.args.get('priority', 'all')
    status_filter = request.args.get('status', 'all')
    search_query = request.args.get('search', '')
    
    tasks = storage.get_all_tasks()
    
    # Apply filters
    if priority_filter != 'all':
        tasks = [t for t in tasks if t.priority.value == priority_filter]
    
    if status_filter == 'completed':
        tasks = [t for t in tasks if t.completed]
    elif status_filter == 'pending':
        tasks = [t for t in tasks if not t.completed]
    elif status_filter == 'overdue':
        now = datetime.now()
        tasks = [t for t in tasks if not t.completed and t.due_date and t.due_date < now]
    
    if search_query:
        tasks = [t for t in tasks if search_query.lower() in t.title.lower() or search_query.lower() in (t.description or '').lower()]
    
    # Calculate stats
    stats = {
        'total': len(storage.get_all_tasks()),
        'completed': len([t for t in storage.get_all_tasks() if t.completed]),
        'pending': len([t for t in storage.get_all_tasks() if not t.completed]),
        'overdue': len([t for t in storage.get_all_tasks() if not t.completed and t.due_date and t.due_date < datetime.now()])
    }
    
    return jsonify({
        'tasks': [task_to_dict(t) for t in tasks],
        'stats': stats
    })

@app.route('/api/tasks/<int:task_id>', methods=['GET'])
def get_task(task_id):
    task = storage.get_task(task_id)
    if task:
        return jsonify(task_to_dict(task))
    return jsonify({'error': 'Task not found'}), 404

@app.route('/api/tasks', methods=['POST'])
def create_task():
    data = request.json
    
    task = Task(
        title=data['title'],
        description=data.get('description'),
        priority=Priority(data.get('priority', 'medium')),
        due_date=datetime.fromisoformat(data['due_date']) if data.get('due_date') else None,
        repeat_frequency=RepeatFrequency(data['repeat_frequency']) if data.get('repeat_frequency') else None,
        reminder_enabled=data.get('reminder_enabled', False)
    )
    
    # Add tags
    for tag_name in data.get('tags', []):
        task.add_tag(Tag(name=tag_name))
    
    # Add subtasks
    for subtask_title in data.get('subtasks', []):
        task.add_subtask(SubTask(title=subtask_title))
    
    storage.add_task(task)
    return jsonify(task_to_dict(task)), 201

@app.route('/api/tasks/<int:task_id>', methods=['PUT'])
def update_task(task_id):
    task = storage.get_task(task_id)
    if not task:
        return jsonify({'error': 'Task not found'}), 404
    
    data = request.json
    task.title = data.get('title', task.title)
    task.description = data.get('description', task.description)
    task.priority = Priority(data.get('priority', task.priority.value))
    task.due_date = datetime.fromisoformat(data['due_date']) if data.get('due_date') else None
    task.repeat_frequency = RepeatFrequency(data['repeat_frequency']) if data.get('repeat_frequency') else None
    task.reminder_enabled = data.get('reminder_enabled', task.reminder_enabled)
    
    # Update tags
    task.tags = []
    for tag_name in data.get('tags', []):
        task.add_tag(Tag(name=tag_name))
    
    # Update subtasks
    task.subtasks = []
    for subtask_title in data.get('subtasks', []):
        task.add_subtask(SubTask(title=subtask_title))
    
    storage.save()
    return jsonify(task_to_dict(task))

@app.route('/api/tasks/<int:task_id>', methods=['DELETE'])
def delete_task(task_id):
    task = storage.get_task(task_id)
    if task:
        storage.delete_task(task_id)
        return jsonify({'message': 'Task deleted'})
    return jsonify({'error': 'Task not found'}), 404

@app.route('/api/tasks/<int:task_id>/toggle', methods=['POST'])
def toggle_task(task_id):
    task = storage.get_task(task_id)
    if task:
        task.completed = not task.completed
        if task.completed:
            task.completed_at = datetime.now()
        else:
            task.completed_at = None
        storage.save()
        return jsonify(task_to_dict(task))
    return jsonify({'error': 'Task not found'}), 404

@app.route('/api/tasks/<int:task_id>/subtasks/<int:subtask_id>/toggle', methods=['POST'])
def toggle_subtask(task_id, subtask_id):
    task = storage.get_task(task_id)
    if task:
        subtask = next((s for s in task.subtasks if s.id == subtask_id), None)
        if subtask:
            subtask.completed = not subtask.completed
            storage.save()
            return jsonify(task_to_dict(task))
    return jsonify({'error': 'Subtask not found'}), 404

@app.route('/api/backup', methods=['GET'])
def backup():
    from flask import Response
    import json
    
    tasks = storage.get_all_tasks()
    backup_data = {
        'backup_date': datetime.now().isoformat(),
        'tasks': [task_to_dict(t) for t in tasks]
    }
    
    return Response(
        json.dumps(backup_data, indent=2, default=str),
        mimetype='application/json',
        headers={'Content-Disposition': 'attachment;filename=backup.json'}
    )

def task_to_dict(task):
    # Get tag objects from storage if tags are stored as IDs
    from storage import TaskStorage
    storage = TaskStorage()
    
    tag_objects = []
    for tag_id in task.tags:
        tag_obj = storage.get_tag(tag_id)
        if tag_obj:
            tag_objects.append(tag_obj)
    
    return {
        'id': task.id,
        'title': task.title,
        'description': task.description,
        'priority': task.priority.value,
        'completed': task.completed,
        'completed_at': task.completed_at.isoformat() if task.completed_at else None,
        'created_at': task.created_at.isoformat(),
        'due_date': task.due_date.isoformat() if task.due_date else None,
        'repeat_frequency': task.repeat_frequency.value if task.repeat_frequency else None,
        'reminder_enabled': task.reminder_enabled,
        'tags': [{'id': t.id, 'name': t.name} for t in tag_objects],
        'subtasks': [{
            'id': s.id,
            'title': s.title,
            'completed': s.completed
        } for s in task.sub_tasks]
    }

def run_web_gui(host='0.0.0.0', port=5000, debug=True):
    """Run the web-based GUI."""
    print(f"🚀 Starting Task Manager Web Interface")
    print(f"📱 Open your browser and go to: http://localhost:{port}")
    print(f"🌐 Accessible from any device on your network")
    app.run(host=host, port=port, debug=debug)

if __name__ == '__main__':
    run_web_gui()
